_config: !include "../../.hpack.config.yaml"

name:                bcc-client
version:             1.0.0
github:              "The-Blockchain-Company/ogmios"
license:             MPL-2.0
author:              "KtorZ <matthias.benkort@gmail.com>"
maintainer:          "matthias.benkort@gmail.com"
copyright:           "2020-2021 KtorZ"
description:         Please see the README on GitHub at <https://github.com/The-Blockchain-Company/ogmios/tree/master/server/modules/bcc-client>
synopsis:            Utilities to build a bcc client using the Shardagnostic mini-protocols
category:            Cardano

extra-source-files:
- LICENSE
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

default-extensions: *default-extensions

library:
  source-dirs: src
  ghc-options: *ghc-options-lib
  dependencies:
    - aeson
    - bytestring
    - bcc-ledger-cole
    - bcc-ledger-core
    - bcc-slotting
    - cborg
    - containers
    - contra-tracer
    - io-classes
    - tbco-monitoring
    - network-mux
    - shardagnostic-consensus
    - shardagnostic-consensus-cole
    - shardagnostic-consensus-bcc
    - shardagnostic-consensus-sophie
    - shardagnostic-network
    - shardagnostic-network-framework
    - typed-protocols
    - typed-protocols-cborg
  build-tools:
  - hspec-discover
