version: "3.5"

services:
  bcc-node:
    image: tbco/bcc-node
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:
      - ./server/config/network/${NETWORK:-mainnet}/bcc-node:/config
      - ./server/config/network/${NETWORK:-mainnet}/genesis:/genesis
      - node-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"

  ogmios:
    image: tbco/ogmios:latest-${NETWORK:-mainnet}
    build:
      context: .
      target: ogmios
      cache_from: [The-Blockchain-Company/ogmios:latest]
    restart: on-failure
    command: [
      "--host", "0.0.0.0",
      "--node-socket", "/ipc/node.socket",
      "--node-config", "/config/bcc-node/config.json"
    ]
    volumes:
      - ./server/config/network/${NETWORK:-mainnet}:/config
      - node-ipc:/ipc
    ports:
      - ${OGMIOS_PORT:-1337}:1337

volumes:
  node-db:
  node-ipc:
